# Copyright 2026 The zb Authors
# SPDX-License-Identifier: MIT

name: Build
on:
  push:
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@v7
      - name: Install zb
        uses: 256lights/setup-zb@06b09ab9711eb574df9c37fa3d626a92ff5376e4
        with:
          zb-version: '0.2.0-beta1'
      - name: Check zb version
        run: zb --version
